# docker compose rm -f && docker compose up

services:
  QM1:
    image: "icr.io/ibm-messaging/mq:latest"
    ports:
      - 9441:9443
      - 1411:1414
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_APP_PASSWORD=passw0rd
      - MQ_ADMIN_PASSWORD=passw0rd
      - MQ_ENABLE_METRICS=true
      - MQ_ENABLE_EMBEDDED_WEB_SERVER=false
    volumes:
      - qm1UCdata:/mnt/mqm
      - ./kdb/qm-kdb:/etc/mqm/pki/keys/mykey
      - ./cluster_config/AutoCluster.ini:/etc/mqm/AutoCluster.ini
      - ./cluster_config/UniCluster.mqsc:/etc/mqm/UniCluster.mqsc
    networks:
      - mqnetwork

  QM2:
    image: "icr.io/ibm-messaging/mq:latest"
    ports:
      - 9442:9443
      - 1412:1414
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM2
      - MQ_APP_PASSWORD=passw0rd
      - MQ_ADMIN_PASSWORD=passw0rd
      - MQ_ENABLE_METRICS=true
      - MQ_ENABLE_EMBEDDED_WEB_SERVER=false
    volumes:
      - qm1UCdata:/mnt/mqm
      - ./kdb/qm-kdb:/etc/mqm/pki/keys/mykey
      - ./cluster_config/AutoCluster.ini:/etc/mqm/AutoCluster.ini
      - ./cluster_config/UniCluster.mqsc:/etc/mqm/UniCluster.mqsc
    networks:
      - mqnetwork

  QM3:
    image: "icr.io/ibm-messaging/mq:latest"
    ports:
      - 9443:9443
      - 1413:1414
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM3
      - MQ_APP_PASSWORD=passw0rd
      - MQ_ADMIN_PASSWORD=passw0rd
      - MQ_ENABLE_METRICS=true
      - MQ_ENABLE_EMBEDDED_WEB_SERVER=false
    volumes:
      - qm1UCdata:/mnt/mqm
      - ./kdb/qm-kdb:/etc/mqm/pki/keys/mykey
      - ./cluster_config/AutoCluster.ini:/etc/mqm/AutoCluster.ini
      - ./cluster_config/UniCluster.mqsc:/etc/mqm/UniCluster.mqsc
    networks:
      - mqnetwork

  mq-test:
    image: "icr.io/ibm-messaging/mq:latest"
    environment:
      - LICENSE=accept
      #- MQ_QMGR_NAME=QMx
      #- MQ_APP_PASSWORD=passw0rd
      - MQ_ENABLE_EMBEDDED_WEB_SERVER=false
      - MQCHLTAB=ccdt.json
      - MQCHLLIB=/tmp/config
      - MQSAMP_USER_ID=app
      - MQSSLKEYR=/tmp/config/mqi/clientkey.kdb
    volumes:
      - ./ccdt/ccdt.json:/tmp/config/ccdt.json
      - ./kdb/mqi-kdb:/tmp/config/mqi
    networks:
      - mqnetwork

volumes:
  qm1UCdata:
    labels:
      - com.ibm.mqucl=clu1
  qm2UCdata:
    labels:
      - com.ibm.mqucl=clu1
  qm3UCdata:
    labels:
      - com.ibm.mqucl=clu1

networks:
  mqnetwork:
    labels:
      - com.ibm.mqucl=clu1
