ibm:
  mq: 
    user: bob
    #queueManager: "*ANY_QM" # uniform_cluster
    queueManager: "EARTH"   # multi-instance Qmgr
    channel: AMS.SVRCONN
    #tempModel: DEV.APP.MODEL.QUEUE
    password: passw0rd
    # applicationName: spring-boot-jms-client # uniform_cluster
    # balancingApplicationType: SIMPLE # uniform_cluster
    reconnect: ANY
    sslBundle: "ibmmq"
    ccdtUrl: file:///tmp/client/ccdt.json

spring:
  jms:
    cache:
      enabled: true
  ssl:
    bundle:
      jks:
        ibmmq:
          # protocol: TLSv1.2
          truststore:
            location: file:///tmp/client/clientkey.jks
            password: "P@ssw0rd"
            type: "JKS"


logging:
  pattern:
    console: "%date %logger{36} - %msg%n"
  level:
    root: INFO
    com:
      ibm:
        mq:
          spring:
            boot: TRACE
