services:
  earth:
    image: "icr.io/ibm-messaging/mq:latest"
    hostname: earth
    ports:
      - 9441:9443
      - 1414:1414
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=EARTH
      - MQ_APP_PASSWORD=passw0rd
      - MQ_ADMIN_PASSWORD=passw0rd
      - MQ_ENABLE_EMBEDDED_WEB_SERVER=true
      - WLP_LOGGING_MESSAGE_FORMAT=basic
    volumes:
      - ./htp/mq.htpasswd:/etc/mqm/mq.htpasswd
      - ../multi-instance/kdb:/tmp/config/sslkeyr
      - ./alice:/tmp/alice
      - ./bob:/tmp/bob

# app, admin - passw0rd, alice, bob - passw0rd